project:
  type: website

website:
  title: "Blog de Pierre Brasseur"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/brasseurp
      - icon: twitter
        href: https://twitter.com/p_brasseur
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

